#!/bin/bash
set -e

PUSH=""

docker build -t solsson/kafka -t "$IMAGE_NAME" ./kafka
PUSH="$PUSH $IMAGE_NAME"

nonroot=$(echo -n $IMAGE_NAME | sed "s|:|:nonroot-|")
docker build -t solsson/kafka:nonroot -t "$nonroot" ./kafka-nonroot
PUSH="$PUSH $nonroot"

# Generatoe entrypoints
docker build -t solsson/kafka-entrypoints ./kafka-entrypoints

function entrypoint_gen {
  echo "# $@"
  script=$1; shift
  name=$(basename $script | sed 's|\.sh$||')
  dfile=./kafka-entrypoints/$name.Dockerfile
  image=$(echo -n $IMAGE_NAME | sed "s|:|:$name-|")
  echo "FROM solsson/kafka" > $dfile
  echo -n 'ENTRYPOINT ["'  >> $dfile
  docker run --rm --entrypoint $script solsson/kafka-entrypoints $@ \
    | sed 's| |", \\\
  "|g'     >> $dfile
  echo '"]'                >> $dfile
  docker build -t $image -f $dfile ./kafka-entrypoints
  PUSH="$PUSH $image"
}

entrypoint_gen ./bin/kafka-server-start.sh ./config/server.properties
entrypoint_gen ./bin/zookeeper-server-start.sh ./cofig/zookeeper.properties
# Entrypoints done

for P in $PUSH; do docker push $P; done
