#!/bin/bash

# like tar's --strip-components but hardcoded 1
unzip-strip() (
    local zip=$1
    local dest=${2:-.}
    local temp=$(mktemp -d) && unzip -d "$temp" "$zip" && mkdir -p "$dest" &&
    shopt -s dotglob && local f=("$temp"/*) &&
    if (( ${#f[@]} == 1 )) && [[ -d "${f[0]}" ]] ; then
        mv "$temp"/*/* "$dest"
    else
        mv "$temp"/* "$dest"
    fi && rmdir "$temp"/* "$temp"
)

echo "Downloading $download_zip_url"
curl -SLs "$download_zip_url" -o /tmp/node-run-dl.tmp

echo "$download_zip_sha256 /tmp/node-run-dl.tmp" | sha256sum -c - || {
  echo "Checksum mismatch, expected/actual:"
  echo "Expected: $download_zip_sha256"
  echo "Actual:   $(sha256sum - < /tmp/node-run-dl.tmp)"
  exit 1
}

if [ $download_strip_dirs = 1 ]; then
  unzip-strip /tmp/node-run-dl.tmp /usr/src/app
  cd /usr/src/app
else
  mkdir /usr/src/app
  cd /usr/src/app
  unzip /tmp/node-run-dl.tmp
fi
rm /tmp/node-run-dl.tmp

npm install --production

npm start
