#!/bin/bash

# like tar's --strip-components but hardcoded 1
unzip-strip() (
    local zip=$1
    local dest=${2:-.}
    local temp=$(mktemp -d) && unzip -d "$temp" "$zip" && mkdir -p "$dest" &&
    shopt -s dotglob && local f=("$temp"/*) &&
    if (( ${#f[@]} == 1 )) && [[ -d "${f[0]}" ]] ; then
        mv "$temp"/*/* "$dest"
    else
        mv "$temp"/* "$dest"
    fi && rmdir "$temp"/* "$temp"
)

download-and-extract() {
  echo "# Downloading $download_zip_url"
  curl -SLs "$download_zip_url" -o /tmp/node-run-dl.tmp

  echo "$download_zip_sha256 /tmp/node-run-dl.tmp" | sha256sum -c - || {
    echo "Aborting due to checksum mismatch"
    echo "Expected: $download_zip_sha256"
    echo "Actual:   $(sha256sum - < /tmp/node-run-dl.tmp)"
    exit 1
  }

  if [ $download_strip_dirs = 1 ]; then
    unzip-strip /tmp/node-run-dl.tmp /usr/src/app
    cd /usr/src/app
  else
    mkdir /usr/src/app
    cd /usr/src/app
    unzip /tmp/node-run-dl.tmp
  fi
  rm /tmp/node-run-dl.tmp
}

if [ -d /usr/src/app ]; then
  echo "# Looks like app is already installed"
  cd /usr/src/app
else
  download-and-extract
fi

if [ -d /usr/src/libs/node_modules ] && [ ! -d /usr/src/app/node_modules ]; then
  echo "# Looks like there are common libs"
  ln -sv /usr/src/libs/node_modules /usr/src/app/node_modules
fi

npm install --production

npm start
